@startuml DIAGRAMA RELACIONAL SS
skinparam linetype ortho

' =====================
' ENTIDADES
' =====================

entity usuario {
  +id : INT <<PK>>
  --
  rol : VARCHAR(20)
  'GR 01
  correo_institucional : VARCHAR(35) <<UQ>>
  nombre : VARCHAR(50)
  apellidos : VARCHAR(50)
  contraseña : VARCHAR(255)
  'CRED 01
  intentos_fallidos : TINY INT UNSIGNED
  cuenta_bloqueada : TINY INT(1) 
  fecha_bloqueo : DATETIME NULL
  'cred 03
  fecha_creacion : DATETIME
  creado_por_id: INT UNSIGNED NULL <<FK>>
  'estos son para cuando suban la imagen de su firma en tu cu!!!!
  rubrica_imagen
  rubrica_hash
  rubrica_ip
  rubrica_fecha_registro
}

entity alumno {
  +  boleta: char(10) UNIQUE <<PK>>
  --
  usuario_id : INT UNIQUE <<FK>>
  celular : VARCHAR(10)
  carrera : VARCHAR(3)
  creditos : TINY INT UNSIGNED
  semestre : TINY INT UNSIGNED 
  

}

entity profesor{
  +id : INT <<PK>>
  --
  usuario_id : INT UNIQUE <<FK>>
  'CRED-04
  academia : VARCHAR(100)
}

entity coordinador {
  +id : INT <<PK>>
  --
  usuario_id : INT UNIQUE <<FK>>
}

entity inicio_sesion {
  +id : INT <<PK>>
  --
  usuario_id : INT UNSIGNED <<FK>>
  fecha_hora : DATETIME
  ip_acceso : VARCHAR(45)
  resultado : TINY INT(1)
} 

entity token_contraseña{
  +id : INT <<PK>>
  --
  usuario_id : INT UNSIGNED <<FK>>
  token : VARCHAR(255)
  fecha_expiracion : DATETIME
  usado: TINY INT(1)
}

entity oferta_servicio{
  +id : INT <<PK>>
  --
  profesor_id : INT <<FK>>
  coordinador_id : INT <<FK>>
  'GR-02
  cupos_ofertados: TINY INT UNSIGNED
  cupos_disponibles: TINY INT UNSIGNED
  'GR-04
  nombre_SISS: VARCHAR(100)
}

entity solicitud_registro {
  +id : INT <<PK>>
  --
  alumno_id : INT UNIQUE <<FK>>
  carrera_id : INT <<FK>>
  'GR-01
  dictamen : TINY INT UNSIGNED NULL
  periodo_registro_id : INT <<FK>>
  oferta_id : INT <<FK>>
  motivacion_oferta : TEXT
  estado_solicitud : VARCHAR(50)
  estado_anterior : VARCHAR(50)
  fecha_aplicacion : DATETIME
  'GR-02
  tipo_rechazo: VARCHAR(50) NULL
  motivo_rechazo : TEXT NULL
  'GR-04
  registro_siss : TINYINT (1)
  'GR-05
  docs_iniciales : TINYINT (1)
  'GR-08
  carta_compromiso : TINYINT (1)
  'GR-11
  expediente: TINYINT (1)
}


entity actividad {
  +id : INT <<PK>>
  --
  solicitud_registro_id : INT <<FK>>
  'AH-01
  titulo : VARCHAR(150)
  descripcion : TEXT
  entregable_esperado : TEXT
  fecha_limite : DATE
  estado : VARCHAR(20)
  fecha_asignacion : DATETIME
  'AH-02
  porcentaje_progreso : TINYINT UNSIGNED
  fecha_completada : DATETIME NULL
}
'estado: sin_comenzar, en_progreso, vencida, completada_en_tiempo, completada_fuera_de_tiempo

entity bitacora {
  +id : INT <<PK>>
  --
  solicitud_registro_id : INT <<FK>>
  'AH-03
  hora_inicio : DATETIME
  hora_fin : DATETIME
  horas_contabilizadas : TINYINT UNSIGNED
  estado : VARCHAR(30)
  fecha_registro : DATE
  'AH-04
  motivo_rechazo : TEXT NULL
  fecha_revision : DATETIME NULL
  revisado_por_id : INT <<FK>> NULL
}
'ESTADO: En curso, Pendiente de revisión, Aprobada, Rechazada


entity registro_bitacora_actividades {
  +id : INT <<PK>>
  --
  bitacora_id : INT <<FK>>
  actividad_id : INT <<FK>>
  'AH-03
  descripcion : TEXT
  porcentaje_avance_registrado : TINYINT UNSIGNED
  evidencia : TEXT
  --
  <<UNIQUE>> (bitacora_id, actividad_id)
}

entity reporte_mensual{
  +id : INT <<PK>>
  --
  solicitud_registro_id : INT <<FK>>
  documento_id : INT UNIQUE <<FK>>
}

entity reporte_global{
  +id : INT <<PK>>
  --
  solicitud_registro_id : INT <<FK>>
  documento_id : INT UNIQUE <<FK>>
}

entity revision_reporte_mensual {
  +id : INT <<PK>>
  --
  reporte_mensual_id : INT <<FK>>
  usuario_id : INT <<FK>>
  tipo_revisor (alumno / profesor / coordinador)
  estado (aprobado / rechazado)
  comentario (si rechazado)
  hash_documento (si aprobado)
  hash_rubrica (si aprobado)
  ip_firma (si aprobado)
  token_tsa (si aprobado)
  fecha
}

entity revision_reporte_global {
  +id : INT <<PK>>
  --
  reporte_global_id : INT <<FK>>
  usuario_id : INT <<FK>>
  tipo_revisor (alumno / profesor / coordinador)
  estado (aprobado / rechazado)
  comentario (si rechazado)
  hash_documento (si aprobado)
  hash_rubrica (si aprobado)
  ip_firma (si aprobado)
  token_tsa (si aprobado)
  fecha
}

entity documento {
  +id : INT <<PK>>
  --
  alumno_id : INT <<FK>>
  creador_id : INT <<FK>>
  'GR-05
  tipo_documento : VARCHAR(50)
  fecha_creacion : DATETIME
  estado_documento : VARCHAR (20)
  ruta_archivo : VARCHAR(255) 
  'GR-07
  aprobado_por_id : INT <<FK>> NULL
  'GR-10
  nombre_expediente: VARCHAR(100) NULL
}

'estado_documento puede ser: "en revision", "aprobado", "rechazado", "con_correciones"

entity cumulo_horas_y_faltas {
  +id : INT <<PK>>
  --
  alumno_id : INT UNIQUE <<FK>>
  'AH-03
  horas_acumuladas : SMALLINT UNSIGNED
  horas_rechazadas : SMALLINT UNSIGNED
  'AH-04
  faltas_acumuladas : TINYINT UNSIGNED
  faltas_consecutivas : TINYINT UNSIGNED
}

' carrera DESEADO
entity carrera {
  +id : INT <<PK>>
  --
  nombre : VARCHAR
}

entity deseo_de_carrera {
  + id : INT <<PK>>
  --
  oferta_id : INT <<FK>>
  carrera_id : INT <<FK>>
  --
  <<UNIQUE>> (oferta_id, carrera_id)
}

' profesorCARACTERISTICA

entity caracteristica {
  +id : INT <<PK>>
  --
}

entity solicitud_caracteristica {
  +id : INT <<PK>>
  --
  profesor_id : INT <<FK>>
  caracteristica_id : INT <<FK>>
}

' CALENDARIO

entity evento_calendario {
  +id : INT <<PK>>
  --
  coordinador_id : INT <<FK>>
  nombre: VARCHAR
  tipo: ENUM("Vacacional", "Inhabil")
  fecha: DATE
  hora: TIME
  fecha_inicio: DATE
  fecha_fin: DATE
}
' RECURSO
entity recurso {
  +id : INT <<PK>>
  --
  coordinador_id : INT <<FK>>
}


entity periodo_registro {
  +id : INT <<PK>>
  --
}

' ANUNCIOS
entity anuncio {
  +id : INT <<PK>>
  --
  usuario_id : INT <<FK>>
}

entity registro_anuncio_visto {
  +id : INT <<PK>>
  --
  alumno_id : INT <<FK>>
  anuncio_id : INT <<FK>>
  --
  <<UNIQUE>> (alumno_id, anuncio_id)
}

' LSS
entity liberacion_proceso {
  +id : INT <<PK>>
  --
  solicitud_registro_id : INT UNIQUE <<FK>>
}

entity evaluacion_desempeño {
  +id : INT <<PK>>
  --
  documento_id : INT UNIQUE <<FK>>
  liberacion_proceso_id : INT UNIQUE <<FK>>
}

entity revision_desempeño {
  +id : INT <<PK>>
  --
  evaluacion_desempeño_id : INT <<FK>>
  usuario_id : INT <<FK>>
  tipo_revisor (alumno / profesor / coordinador)
  estado (aprobado / rechazado)
  comentario (si rechazado)
  hash_documento (si aprobado)
  hash_rubrica (si aprobado)
  ip_firma (si aprobado)
  token_tsa (si aprobado)
  fecha
}


entity solicitud_baja {
  +id : INT <<PK>>
  --
  alumno_id <<FK>>       
  solicitante_id <<FK>>
  coordinador_id <<FK>>
  estado 
  comentario
  fecha
}




' =====================
' RELACIONES
' =====================

'SOLICITUD DE BAJA
alumno ||--|| solicitud_baja : "1:1 \n corresponde"
usuario ||--o{ solicitud_baja : "1:N \n solicita"
coordinador ||--o{ solicitud_baja : "1:N \n gestiona"


' USUARIO 
usuario ||--o{ token_contraseña : "1:N \n genera"
usuario ||--o{ inicio_sesion : "1:N \n registra"


usuario ||--|| alumno: "1:1 \n es un"

usuario ||--|| profesor: "1:1 \n es un"
usuario ||--|| coordinador : "1:1 \n es un"


usuario ||--o{ anuncio : "1:N \n publica"
usuario ||--o{ documento : "1:N \n crea"
usuario ||--o{ revision_reporte_mensual : "1:N \n registra"
usuario ||--o{ revision_reporte_global : "1:N \n registra"



' REPORTE
reporte_mensual ||--o{ revision_reporte_mensual : "1:N \n tiene"

reporte_mensual ||--|| documento : "1:1 \n es un"

reporte_global ||--o{ revision_reporte_global : "1:N \n resume"
reporte_global ||--|| documento : "1:1 \n es un"




'ALUMNO
alumno ||-o{ documento : "1:N \n corresponde"
alumno ||--|| cumulo_horas_y_faltas : "1:1 \n tiene"
alumno ||--o{ registro_anuncio_visto : "1:N \n genera"
alumno ||--|| solicitud_registro : "1:1 \n corresponde"


'ANUNCIO
anuncio ||--o{ registro_anuncio_visto : "1:N \n tiene"

' PROFESOR
profesor ||--o{ oferta_servicio: "1:N \n corresponde"
profesor ||--o{ solicitud_caracteristica : "1:N \n tiene"  
profesor ||--o{ bitacora : "1:N \n revisa"
profesor ||--o{ actividad : "1:N \n asigna"

'CARACTERISTICA
caracteristica ||--o{ solicitud_caracteristica : "1:N \n corresponde"

'OFERTA
oferta_servicio ||--o{ deseo_de_carrera : "1:N \n registra"
oferta_servicio ||--o{ solicitud_registro: "1:N \n tiene"


'COORDINADOR
coordinador ||--o{ oferta_servicio: "1:N \n revisa"
coordinador ||--o{ recurso: "1:N \n gestiona "
coordinador ||--o{ evento_calendario: "1:N \n gestiona"

coordinador ||--o{ usuario : "1:N \n crea"
coordinador ||--o{ documento : "1:N \n revisa"

'CARRERA
carrera ||--o{ deseo_de_carrera : "1:N \n se requiere"
carrera ||--o{ solicitud_registro: "1:N \n se requiere"

' SOLICITUD
solicitud_registro }o--|| periodo_registro : "N:1 \n escoge"
solicitud_registro ||--o{ bitacora : "1:N \n le corresponde"
solicitud_registro ||--o{ actividad : "1:N \n le corresponde"
solicitud_registro ||--|| liberacion_proceso : "1:1 \n solicita"
solicitud_registro ||--o{ reporte_mensual: "1:N \n le corresponde"
solicitud_registro ||--|| reporte_global: "1:1 \n le corresponde"


' BITACORA
bitacora ||--o{ registro_bitacora_actividades : "1:N \n contiene"
actividad ||--o{ registro_bitacora_actividades : "1:N \n es registrada en"


'EVALUACIÓN_DESEMPEÑO
evaluacion_desempeño ||--|| documento : "1:1 \n es un"
evaluacion_desempeño ||--o{ revision_desempeño : "1:N \n tiene"
usuario ||--o{ revision_desempeño : "1:N \n registra"

'LIBERACIÓN_PROCESO
liberacion_proceso ||--|| evaluacion_desempeño : "1:1 \n corresponde"




@enduml